# -*- coding: utf-8 -*-
"""Gemini API Usage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l_epdJrXbFm-9lTKlT_uUjD62Zk6PL8u

## 13 July - Interacting with the Gemini API
"""

from google import genai
from google.colab import userdata

key = userdata.get('SY_API_KEY')

client = genai.Client(api_key = key)
response = client.models.generate_content

response = client.models.generate_content(
    model = "gemini-3.1-flash-lite",
    contents = "Explain how AI works in detail in 5 bulleted points"
)

print(response.text)

# how many words this used (roughly)
print(response.usage_metadata.prompt_token_count)
print(response.usage_metadata.candidates_token_count)
print(response.usage_metadata.total_token_count)

# To prettify the output - but Optional
from IPython.display import Markdown, display

display(Markdown(response.text))



# Making a Google Translator using Gemini

from google.genai import types, errors

def translate_text(text_to_translate, target_language):

  try:
    response = client.models.generate_content(
      model="gemini-3-flash-preview",
      contents=text_to_translate,
      config=types.GenerateContentConfig(
        system_instruction=f"Translate this into {target_language}. Keep the same feeling. Reply with only the text."
      )
    )
    return {"status":"Success",
      "data": response.text,
      "tokens_used": response.usage_metadata.total_token_count}

  except errors.APIError as e:
    return {"status":"Error","data":e.message,"tokens_used":0}

translate_text("Hello, Good Evening! Are you excited about today's session" , "Spanish" )



"""# 15 July - Fine-Tuning and Managing AI Requests"""

from google import genai
from google.colab import userdata
from google.genai import types, errors

key = userdata.get('SY_API_KEY')

client = genai.Client(api_key = key)

#temperature

response = client.models.generate_content(
    model="gemini-3.1-flash-lite",
    contents="Suggest a name for a coffee shop.",
    config=types.GenerateContentConfig(
        temperature=0.0 #close to deterministic output
    )
)

print(response.text)

# temperature

response = client.models.generate_content(
    model="gemini-3.1-flash-lite",
    contents="Suggest a name for a coffee shop.",
    config=types.GenerateContentConfig(
        temperature = 1.5
    )
)

print(response.text)



# max_output_tokens

response = client.models.generate_content(
    model="gemini-3.1-flash-lite",
    contents="Explain why exercise is important.",
    config=types.GenerateContentConfig(
        max_output_tokens = 250
    )
)

print(response.text)

reason = response.candidates[0].finish_reason
print(reason)



# stop_sequences

response = client.models.generate_content(
    model="gemini-3.1-flash-lite",
    contents="Name 10 popular fruits in India",
    config=types.GenerateContentConfig(
        stop_sequences= ["Orange", "Grapes", "Apple"]
    )
)

print(response.text)



try:

    response = client.models.generate_content(
        model="gemini-3.1-flash-lite",
        contents="Generate a 5000 word poem on rain",
        config=types.GenerateContentConfig(
            http_options=types.HttpOptions(
                timeout=12000
            )
        )
    )

    print(response.text)

except errors.APIError as e:
    print("API Error:", e)

except Exception:
    print("Something went wrong.")

# except Exception as e:
#     print("Request failed.")
#     print(e)



def generate_notes(topic, creative=False):

    temp = 1.2 if creative else 0.2

    try:

        response = client.models.generate_content(
            model="gemini-3.1-flash-lite",
            contents=f"Create notes on {topic}.",
            config=types.GenerateContentConfig(
                temperature=temp,
                max_output_tokens=1000,
                # stop_sequences=["###"],
                http_options=types.HttpOptions(
                    timeout=15000
                )
            )
        )

        return {
            "notes": response.text.strip(),
            "finish_reason": response.candidates[0].finish_reason,
            "tokens": response.usage_metadata.total_token_count
        }

    except Exception:
        return {
            "notes": "Request Failed",
            "finish_reason": "ERROR",
            "tokens": 0
        }

result = generate_notes(
    "AI in Cricket",
    creative=False
)

print(result)

print(result['notes'])



"""## *17* July - Building a Resilient AI Pipeline"""

# How to attach a document in the code for reference.

from google import genai
from google.colab import userdata
from google.genai import types, errors

key = userdata.get('SY_API_KEY')

client = genai.Client(api_key = key)

from google.colab import files

# files.upload()

uploaded_file = client.files.upload(
    file="API_key_setup.pdf"
)

response = client.models.generate_content(
    model="gemini-3.1-flash-lite",
    contents=[
        uploaded_file,
        "Summarize this PDF in 5 bullet points."
    ]
)

print(response.text)

# To prettify the output - but Optional
from IPython.display import Markdown, display

display(Markdown(response.text))

# Homework: Try to connect a file on Google Drive through link and get the output





"""Imagine a cloud company gets messy, plain-English complaints from customers all day: "the site is down," "everything is so slow," "I can't log in." **Our tool needs to read a raw complaint, and automatically:**

- Work out which system is likely affected
- Judge how severe the issue is
- Recommend an action
- Package it all cleanly — and never crash, even if the network misbehaves
"""



"""

1.   "Our database is not responding and users are seeing 500 Internal Server Error."
2.   "Customers cannot access the website because the network connection keeps dropping."
3.   "The login page loads, but clicking the Sign In button does nothing."

"""

from google import genai
from google.colab import userdata
from google.genai import types, errors

key = userdata.get('SY_API_KEY')
client = genai.Client(api_key = key)

# Incident triage is the rapid assessment step where IT and operations teams determine the scope, severity, and ownership of a new incident before active resolution begins.

def triage_incident(raw_complaint):

  #detailed system instruction which has persona, task and output format
  system_blueprint = """
    You are an automated cloud server triage engine.
    Extract data into this exact schema:
    System: [Database, Frontend, Network, or Unknown]
    Severity: [High, Medium, Low]
    Action: [Restart, Scale, Patch, or Investigate]

    EXAMPLE:
    Input: "Our database connection pool is exhausted! 500 errors."
    Output: System: Database | Severity: High | Action: Restart
    """

  try:
    response = client.models.generate_content(

            model="gemini-3.1-flash-lite",
            contents=f"Alert Text: <{raw_complaint}>",

            #parameter tuning
            config=types.GenerateContentConfig(
                system_instruction=system_blueprint,
                temperature=0.0,
                max_output_tokens=250,
                http_options=types.HttpOptions(timeout=15000)
            )
        )
    #removing extra spaces
    raw_output = response.text.strip()

    #final output when the code runs successfully
    return {"status": "Success", "payload": raw_output,
                "tokens": response.usage_metadata.total_token_count}

  except errors.APIError as e:
      return {"status": "Pipeline Error", "payload": str(e.message), "tokens": 0}

  except Exception as e:
      return {"status": "Pipeline Error", "payload": str(e), "tokens": 0}

result = triage_incident("The login page loads, but clicking the Sign In button does nothing")

print(result)



import time

def resilient_triage_orchestrator(complaint_text, max_retries=3):
    print("--- STARTING TRIAGE ---")

    for attempt in range(1, max_retries + 1):
        print(f"Attempt {attempt} of {max_retries}...")
        report = triage_incident(complaint_text)

        if report["status"] == "Success":
            print("Success!")
            return report

        print(f"Attempt {attempt} failed. Retrying in 2 seconds...")
        time.sleep(2)

    print("All retries used up without success.")
    return report

